name: Multipule runner and choose jobs
on:
  workflow_dispatch:
    inputs:
        runner:
            description: 'Select the runner to run the job'
            required: true
            default: 'ubuntu-latest'
            type: choice
            options:
                - ubuntu-latest
                - windows-latest
                - macos-latest
        jobs-name:
            description: 'Select the job to run'
            required: true
            default: 'build'
            type: choice
            options:
                - build-job
                - test-job
                - deploy-job
jobs:
    build-job:
        if: ${{ github.event.inputs.jobs-name == 'build-job' }}
        runs-on: ${{ github.event.inputs.runner }}
    test-job:
        if: ${{ github.event.inputs.jobs-name == 'test-job' }}
        runs-on: ${{ github.event.inputs.runner }}
    deploy-job:
        if: ${{ github.event.inputs.jobs-name == 'deploy-job' }}
        runs-on: ${{ github.event.inputs.runner }}
