name: Build nodejs application using github actions

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  buildnodejs:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install nodejs version 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests using npm
        run: npm test

      - name: Build the application using npm
        run: npm run build

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v7
        with:
          name: build-artifact
          path: dist/
